name: 'Release'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        type: string
        required: true

permissions: write-all

jobs:
  prepare:
    runs-on: [ubuntu-22.04]
    outputs:
      version_tag: ${{ steps.version_tag.outputs.value }}
      build_date: ${{ steps.build_date.outputs.value }}
      dockerfile_path: ${{ steps.determine_dockerfile.outputs.dockerfile }}
    steps:
      - name: Format version tag
        shell: bash
        id: version_tag
        env:
          INPUT_TAG: ${{ github.event.inputs.version }}
        run: |
          TAG=${INPUT_TAG#v}
          echo "::set-output name=value::v$TAG"
      - name: Build date
        shell: bash
        id: build_date
        run: echo "::set-output name=value::$(date +%FT%T%z)"

      - name: Determine Dockerfile
        id: determine_dockerfile
        run: |
          if [[ "${{ github.event.inputs.version }}" == v1* ]]; then
            echo "::set-output name=dockerfile::Dockerfile"
          elif [[ "${{ github.event.inputs.version }}" == v2* ]]; then
            echo "::set-output name=dockerfile::Dockerfile-v2"
          else
            echo "::set-output name=dockerfile::Dockerfile"  # Default to Dockerfile if not v1 or v2
          fi

  docker:
    needs:
      - prepare
    env:
      SERVICE: tradelogs
      VERSION_TAG: ${{ needs.prepare.outputs.version_tag }}
      BUILD_DATE: ${{ needs.prepare.outputs.build_date }}
    runs-on: [ubuntu-22.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Gcloud Auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCR_CREDENTIALS }}'
    
      - name: Setup Gcloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Configure docker
        run: gcloud auth configure-docker

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-${{ env.SERVICE }}-buildx

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ needs.prepare.outputs.dockerfile_path }}  # Use the corresponding Dockerfile version
          push: true
          build-args: |
            VERSION=${{ env.VERSION_TAG }}
            GIT_HASH=${{ github.sha }}
            BUILD_DATE=${{ env.BUILD_DATE }}
          labels: |
            kyber.network.schema-version=1.0
            kyber.network.vcs-ref=${{ github.sha }}
            kyber.network.version=${{ env.VERSION_TAG }}
            kyber.network.name=${{ env.SERVICE }}
          tags: |
            asia.gcr.io/kyber-operation/foundation/trading/${{ env.SERVICE }}:latest
            asia.gcr.io/kyber-operation/foundation/trading/${{ env.SERVICE }}:${{ env.VERSION_TAG }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Move Docker cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  release:
    needs:
      - prepare
      - docker
    runs-on: [ubuntu-22.04]
    env:
      VERSION_TAG: ${{ needs.prepare.outputs.version_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.22.x"

      - name: Setup Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Create tag
        run: |
          git tag -d "$VERSION_TAG" 2> /dev/null || echo "Release tag '$VERSION_TAG' does NOT exist"
          git tag --annotate --message "tradelogs $VERSION_TAG" "$VERSION_TAG"
          git push origin "refs/tags/$VERSION_TAG"

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ env.VERSION_TAG }}
          prerelease: false
          name: "tradelogs ${{ env.VERSION_TAG }}"
